<document>
    <ol_list>
        <list_item>
            <paragraph>1.1</paragraph>
        </list_item>
        <list_item>
            <paragraph>1.2</paragraph>
        </list_item>
    </ol_list>
    <ul_list>
        <list_item>
            <paragraph>2.1</paragraph>
        </list_item>
        <list_item>
            <paragraph>2.2</paragraph>
        </list_item>
    </ul_list>
</document>
