<document>
    <ul_list>
        <list_item>
            <paragraph>1</paragraph>
            <ul_list>
                <list_item>
                    <paragraph>1.1</paragraph>
                </list_item>
                <list_item>
                    <paragraph>1.2</paragraph>
                </list_item>
                <list_item>
                    <paragraph>1.3</paragraph>
                </list_item>
                <list_item>
                    <paragraph>1.4</paragraph>
                </list_item>
                <list_item>
                    <paragraph>2</paragraph>
                </list_item>
            </ul_list>
        </list_item>
    </ul_list>
</document>
